version: 2.1

docker_default: &docker_default
  docker:
    - image: cimg/node:18.4.0

commands:
  build_command:
    steps:
      - checkout
      - run:
          name: "install packages"
          command: npm install
      - run:
          name: "build react app"
          command: npm run build
      - save_cache:
          key: "node_modules"
          paths:
            - /node_modules
      - save_cache:
          key: "build_folder"
          paths:
            - /build
  test_command:
    steps:
      - checkout
      - restore_cache:
          keys:
            - "node_modules"
      - run:
          name: "testing app"
          command: npm run test

jobs:
  build:
    <<: *docker_default
    steps:
      - build_command
  test:
    <<: *docker_default
    steps:
      - test_command

workflows:
  React_App:
    jobs:
      - build
      - test:
          requires:
            - build
